config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  get 'mentorings', to: "pages#mentorings"

  ActiveAdmin.routes(self)
  resources :game_skills, only: [:update]
  resources :users, only: [:show]
  resources :challenges, only: [:index]
  resources :skills, only: [:index, :show]
  resources :games, only: [:create, :show, :update, :index]
  resources :game_skills, only: [] do
    resources :messages, only: [:create, :index, :destroy]
  end
  # get 'games/:id/chat', to: "games#chat", as: "chat"
  # get 'challenges/index'
  # get 'skills/index'

  mount Attachinary::Engine => "/attachinary"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :challenges
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  belongs_to :category
  has_many :challenge_skills
  has_many :skills, through: :challenge_skills
  has_many :games
  has_many :constraints
  validates :title, presence: true
  validates :title, uniqueness: true
  # validates :description, presence: true

  include PgSearch
  pg_search_scope :pgsearch,
    against: [:title, :description],
    associated_against: { skills: [:title, :description] },
    using: {  tsearch: { prefix: true, any_word: true },
              dmetaphone: { any_word: true, sort_only: true },
              trigram: { threshold: 0.3 }
            },
    ignoring: :accents


end

app/models/challenge_skill.rb
class ChallengeSkill < ApplicationRecord
  belongs_to :skill
  belongs_to :challenge
end

app/models/constraint.rb
class Constraint < ApplicationRecord
  belongs_to :challenge
  has_many :games
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  belongs_to :challenge
  belongs_to :constraint
  has_many :game_skills
  has_many :skills, through: :game_skills

  def done?
    game_skills.map{|gs| !gs.rating.nil? }.reduce(:&)
  end

  def average
    (game_skills.select( &:rating ).map(&:rating).sum.to_f / game_skills.size).round(2)
  end
end

app/models/game_skill.rb
class GameSkill < ApplicationRecord
  belongs_to :game
  belongs_to :skill
  belongs_to :mentor, class_name: "User"
  has_one :user, through: :game
  has_one :challenge, through: :game
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :game_skill
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :game_skills
  has_many :games, through: :game_skills
  has_many :challenge_skills
  has_many :challenges, through: :challenge_skills
  has_many :categories, through: :challenges
  has_many :users
  has_many :experts, foreign_key: :specialty_id, class_name: "User"
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  has_attachment :photo

  has_many :mentor_game_skills, foreign_key: :mentor_id, class_name: "GameSkill"
  has_many :games
  has_many :game_skills, through: :games
  has_many :skills, through: :game_skills
  has_many :messages
  belongs_to :specialty, class_name: "Skill"
  # validates :first_name, presence: true
  # validates :pseudo, presence: true
  # validates :pseudo, uniqueness: true


  def full_name
    "#{first_name.capitalize} #{last_name.capitalize}"
  end

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:gender] = auth.extra.raw_info.gender
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

  def unfinished_challenges
    games
    .select { |game| !game.done? }
    .map(&:challenge)
  end

  def potential_mentors(skill)
    User.where.not(id: self.id)
        .joins(:game_skills)
        .where(game_skills: { skill: skill })
        .where.not(game_skills: { rating: nil })
        .select { |user| user.mentor?(skill) }
  end

  def validated_skills
    Skill.joins(:game_skills)
         .where.not(game_skills: {rating: nil})
         .joins(:games)
         .where(games: {user: u})
         .uniq
  end


  def ratings(skill)
    GameSkill.where(skill: skill)
             .where.not(rating: nil)
             .joins(:game)
             .where(games: {user: self})
             .map(&:rating)
  end

  def number_actions_with(skill)
    ratings(skill).size
  end

  def average(skill)
    ratings = ratings(skill)
    ratings.size >= 3 ? (ratings.reduce(:+).to_f / ratings.size).round(2) : false
  end

  def mentor?(skill)
    average = average(skill)
    (average && average >= 8) ? average : false
  end

  def experts(skill)
    User.where(specialty: skill)
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def create
    @challenge = Challenge.find_by(title: params["commit"])
    @game = Game.find_by(  user: current_user, challenge: @challenge )
    unless @game
      @game = Game.create(  user: current_user, challenge: @challenge )
      @challenge.skills.each do |skill|
        mentors = current_user.potential_mentors(skill)
        mentor = mentors ? mentors.sample : skill.experts.sample
        GameSkill.create( game: @game, skill: skill, mentor: mentor )
      end
    end
    redirect_to @game
  end

  def show
    @game = Game.find(params[:id])
  end

  def update
    @game = Game.find(params[:id])
    constraint = Constraint.find_by(title: params["commit"])
    @game.update(constraint: constraint)
    redirect_to @game
  end

  def index
    @games = current_user.games
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def mentorings
    @mentorings = current_user.mentor_game_skills
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # def picture
  #   current_user.photo = picture_params[:photo]
  #   current_user.save
  #   redirect_to edit_user_path(current_user)
  # end

  def show
  end



  # def edit
  #   @user = current_user
  # end

  # def update
  #   current_user.update(update_params) ? (redirect_to root_path) : (render :edit)
  # end

  # private

  # def update_params
  #   params.require(:user).permit(:first_name, :last_name, :pseudo, :photo)
  # end

  # def picture_params
  #   params.require(:user).permit(:photo)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/helpers/game_skills_helper.rb
module GameSkillsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="aware-wrapper bg-blue">

<h1><span>S</span>ALUT <%= current_user.first_name.upcase if current_user %>,</h1>
<h1>À QUELLE ACTION VEUX TU</h1>
<h1>T'ATTAQUER AUJOURD'HUI ?</h1>

  <div class="container">

    <%= simple_form_for :selected_challenges, url: challenges_path, method: :get do |f| %>
      <div class="research">
        <%= f.input :words, input_html: { class: "search" }, label: false, placeholder: "ex : créer une vidéo" %>
        <button type="submit" class="btn btn-default" style="margin-bottom: 15px;">
          <i class="fa fa-search"></i>
        </button>
      </div>
      <div class="row">
          <div class="col-xs-12">
            <%= f.submit "Mes actions inachenées", class: "aware-button btn btn-default"  %>
          </div>
          <div class="col-xs-12">
            <%= f.submit "M'inspirer", class: "aware-button btn btn-default"  %>
          </div>
      </div>

    <% end %>
  </div>
</div>

app/views/pages/mentorings.html.erb
<div class="aware-wrapper bg-orange">

  <h1>Mes mentorings</h1>


  <div class="container">

    <div class="row">
      <% @mentorings.each do |mentoring| %>
        <div class="col-xs-12">
          <h2><%= mentoring.user.first_name %> -
          <% if mentoring.rating %>
            <%= mentoring.rating %>/10
          <% else %>

            <%= simple_form_for mentoring do |f| %>
              <%= f.input :rating %>
              <%= f.submit "Noter" %>
            <% end %>



          <% end %>
          </h2>
          <h3><%= mentoring.skill.title %> </h3>
          <h4><%= mentoring.challenge.title %></h4>
          <p><%= mentoring.challenge.description %></p>
        <%= link_to "Discuter", game_skill_messages_path(mentoring), class: "btn btn-default" %>
        <p><%= link_to "Lien vers le projet", "#" %></p>
        <hr>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon bg-blue">
  <!-- Logo -->

  <% if !current_user.nil? && !current_user.photo.nil? %>
      <%= cl_image_tag current_user.photo.path, class: "avatar", crop: :fill %>
  <% end %>

  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <% if !current_user.nil? %>
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <%= link_to current_user do %>
            <i class="fa fa-user"></i> Profile
          <% end %>
        </li>
        <li>
          <%= link_to root_path do %>
            <i class="fa fa-home"></i> Home
          <% end %>
        </li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>
    </div>
  <% else %>
    <div class="color-white">
      <%= link_to "S'inscrire", new_user_registration_path, class: "color-white" %> /
      <%= link_to "Se connecter", new_user_session_path, class: "color-white" %>
    </div>
  <% end %>
</div>