config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'

  get 'mentorings', to: "pages#mentorings"

  ActiveAdmin.routes(self)
  resources :game_skills, only: [:update]
  resources :users, only: [:show]
  resources :challenges, only: [:index]
  resources :skills, only: [:index, :show]
  resources :games, only: [:create, :show, :update, :index]
  resources :game_skills, only: [] do
    resources :messages, only: [:create, :index, :destroy]
  end
  # get 'games/:id/chat', to: "games#chat", as: "chat"
  # get 'challenges/index'
  # get 'skills/index'

  mount Attachinary::Engine => "/attachinary"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  belongs_to :category
  has_many :challenge_skills
  has_many :skills, through: :challenge_skills
  has_many :games
  has_many :constraints
  validates :title, presence: true
  validates :title, uniqueness: true
  # validates :description, presence: true

  include PgSearch
  pg_search_scope :pgsearch,
    against: [:title, :description],
    associated_against: { skills: [:title, :description] },
    using: {  tsearch: { prefix: true, any_word: true },
              dmetaphone: { any_word: true, sort_only: true },
              trigram: { threshold: 0.3 }
            },
    ignoring: :accents


end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index ]

  def index
    if params["commit"] == "Mes missions inachenées"
      if current_user
        @challenges = current_user.unfinished_challenges.sample(3)
      else
        redirect_to new_user_session_path
      end
    elsif params["commit"] == "M'inspirer"
      @challenges = Challenge.all.sample(3)
    else
      @challenges = Challenge.pgsearch(challenges_params[:words]).sample(3)
    end
  end

  private

  def challenges_params
    params.require(:selected_challenges).permit(:words)
  end

end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/index.html.erb
<div class="aware-wrapper bg-green">
<h1>Choisi une action :</h1>

  <div class="container">

    <div class="row">

<% if @challenges.empty? %>
  <p>rien trouvé...</p>
  <%= link_to "essaye à nouveau", root_path %>
<% else %>
  <%= simple_form_for :selected_challenge, url: games_path, method: :post do |f| %>
    <% @challenges.each do |challenge| %>
        <div class="col-xs-12">
          <%= f.submit challenge.title, class: "aware-button btn btn-default"  %>
        </div>
    <% end %>
  <% end %>
<% end %>

    </div>
  </div>
</div>